- - - 
<!-- *********8************날짜****************************** -->
# 061118 MONDAY  


## <strong> 1. References </strong>


- 다시 되짚어보는 Hello World

> https://helloworldjavascript.net/pages/290-exception.html


- module 을 이용한 js 파일 나누기

> https://jakearchibald.com/2017/es-modules-in-browsers/




<br>

____
____


## <strong> 2. Today I learned </strong>


<!-- *********************첫번째 제목********************** -->
## <span style="color:#595EFF"> [JS] 1-1. 예외 처리 </span>    


### 예외 처리 exception handling

___

JavaScript에는 코드 실행 중에 `예기치 못한 에러가 발생`했을 때, 이로부터 코드의 실행 흐름을 `복구할 수 있는 기능`


코드의 실행이 중단되어 (에러가 발생하여) 그 시점에 실행 중이었던 작업을 완료할 수 없게 되면, 불편함을 초례


코드의 실행 흐름을 원상복구할 수 있는 기능을 제공


<br />

`try...catch...finally` 구문을 이용해라!

replit 예제 

> https://repl.it/@beigenut/Try-Catch-Finally-gumun-hwalyong-yeje




<br></br>

`try` 블록 바로 뒤에 `finally` 블록이 오면, finally 블록에 있는 코드는 try 블록 안에서의 `에러 발생 여부와 관계 없이 무조건 실행`




- 에러가 안 났을 때: `try - finally`
- 에러가 났을 때: `try - 에러 발생 - catch - finally`




<br></br>

### Try .. Finally 예제


____

```js
for (let i of [1, 2, 3]) {
  try {
    if (i === 3) {
      break;
    }
  } finally {
    console.log(`현재 i의 값: ${i}`);
  }
}
```

출력 결과

```
현재 i의 값은 1 
현재 i의 값은 2 
현재 i의 값은 3
``` 





<br></br>

### Try Catch Finally 종합 예제


____

```js
try {
  console.log('try');
  new Array(-1); // RangeError: Invalid array length
} catch (e) {
  console.log('catch');
} finally {
  console.log('finally');
}
```

출력 결과 

```
try
catch
finally
```

`에러 발생 부분을 주석` 처리하였을 때 결과

```
try
finally
```



<br></br>

### 에러를 일부로 발생시켜야 할 경우

___


```js 
const even = parseInt(prompt('짝수를 입력하세요'));
if (even % 2 !== 0) {
  throw new Error('짝수가 아닙니다.');
  // 형태는 반드시 생성자 함수 그리고 throw 를 사용
}
```

`Error 생성자`는 어디서나 사용될 수 있고,

`e.name`, `e.message` 객체를 포함하고 있다





<br />

`에러의 종류를 구분`해야 하거나 `에러 객체에 기능을 추가`해야 할 필요 Error를 상속받는 `클래스`를 만들어서, `throw 구문`에서 이 `클래스를 대신 사용`



```js
class MyError extends Error {
  constructor(value, ...params) {
    super(...params);
    this.value = value;
    this.name = 'MyError';
  }
}

try {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new MyError(even, '짝수가 아닙니다.');
  }
} catch (e) {
  if (e instanceof MyError) {
    console.log(e.value);
  }
}
```

- instanceof : arr instanceof Array  -> true 반환하는 매소드









<br></br>

___
### 동기식 호출 스택과 에러 인지 관계
___


```js
function add(x, y) {
  new Array(-1) // 에러 발생
  return x + y;
}

function add2(x) {
  try {             // try 는 에러 발생한 곳이 아닌 다른 곳
  // 그 다음 호출 스택에서 try 블록이 있는지 계속 돌려보며 확인한다
  return add(x, 2); // `add`를 호출
  }catch (e) {
    alert('Caught the error at add2()!')
  }    
}

function add2AndPrint(x) {
  // try {} catch (e) {} 를 여기서 선언해도 add() 에서의 에러를 잡을 수 있다
  const result = add2(x); // `add2`를 호출
  console.log(result); // `console.log`를 호출
}

add2AndPrint(3); // `add2AndPrint`를 호출
```





___

### 비동기식 호출 스택과 에러 인지 관계
___


```js
function add(x, y) {
  setTimeout(() => {
    new Array(-1) // 에러 발생
  })
  return x + y;
}
```

비동기식 함수에서 (setTImeout, eventListener, ..) try {} 블록이 에러 발생 지점 안에 있으면 `error 를 잡기 어렵다` 

.
.
.


`Call Stack` 에서 실행에 필요한 모든 함수들이 쌓여올라가고 비동기 함수로 쓰여진 부분은 `실행 대기중`

Call Stack에 쌓여진 `함수들이 다 실행`되고, `비워진 상태`에서는 특정 함수에 포함되어 있던 `try {} 블록을 더 이상 읽을 수 가 없게` 된다





<br></br>

___

### 비동기식 호출 스택, 에러 인지 가능 코드

___


> https://codepen.io/dbeat999/pen/bKqdwW



```html
<button>버튼</button>
```

```js
const buttonEl = document.querySelector('button');

try { // 비동기 함수 밖에서 try {} 을 작성한다
  buttonEl.addEventListener('click', e => {
    try {
      new Array(-1);
      alert('버튼이 눌렸습니다.');      
    } catch (e) {
      alert('이벤트 리스너 안에서 에러가 발생했습니다.');
    }
  })  
} catch (e) {
  alert('에러가 발생했습니다.'); // 작동 안 함, 이미 위에서 caught
}
```



<br></br>

___

### 원하는 값을 입력하지 않으면 에러를 출력하는 예제


___


- Promise 와 .then 매소드를 이용해서 작성한다


Promise 가 갖는 3가지 상태 

  - pending - Promise 객체에 결과값이 채워지지 않은 상태
  - fulfilled - Promise 객체에 결과값이 채워진 상태
  - rejected - Promise 객체에 결과값을 채우려고 시도하다가 에러가 난 상태



<br />

```js
const p = new Promise(resolve => {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new Error('짝수가 아닙니다.');
  } else {
    resolve(even);
  }
});

p.then(even => {
  return '짝수입니다.';
}, e => {
  return e.message;
}).then(alert);


// or 

// p.then(even => {
//   return '짝수입니다.';
// }).catch (e => { // promise 에는 .catch 매소드 존재 for error
//   return e.message;
// }).then(alert);
```




<br></br>

___

### async await 비동기 함수와 에러 처리

___


```js
async function func() {
  try {
    const res = await fetch('https://nonexistent-domain.nowhere');
  } catch (e) {
    console.log(e.message);
  }
}

func(); // 출력 결과: Failed to fetch
```

코드 작성은 동기식 함수와 같이 쓸 뿐 아니라, 동기식 코드와 동일하게 작동한다









___


<br></br>

<!-- *********************첫번째 제목********************** -->
## <span style="color:#595EFF"> [JS] 2-1. Module 사용 </span>    

### 모듈 사용 방법

___

현재로써는 html 에서 type='sctript' 처럼 사용은 불가

```html
<script type="module" src="index.mjs"></script>
```


<br />

따라서 몇 가지 사용 방법이 있는데, 그 중 하나는

```html
<script type="module">
  import {addTextToBody} from './utils.js';

  addTextToBody('Modules are pretty cool.');
</script>
```

```js
// utils.js
export function addTextToBody(text) {
  const div = document.createElement('div');
  div.textContent = text;
  document.body.appendChild(div);
}
```

또는 `WebPack`, `Parcel` 과 같은 빌드/모듈 번들러를 활용해서 변환한다








<br></br>

___

### 모듈 스코프 
___


모듈 내부의 가장 바깥 스코프 (ex. line 1) 에서 이름을 `선언하더라도`, 전역 스코프가 아니라 `모듈 스코프에서 선언`

.
.
.

여러 모듈의 가장 바깥쪽에서 같은 이름으로 변수, 함수, 클래스를 선언하더라도, `서로 다른 스코프에서 선언`되기 때문에 `이름의 충돌이 생길 일이 없다`






<br></br>

___

### 다른 모듈에서 선언된 변수를 불러오기
___


현재 모듈에서 모듈 전역으로 사용하고 싶은 변수를..

```js
// variables.js
const foo = 'bar';
const spam = 'eggs';

function add(x, y) {
  return x + y;
}

class Person {
  // ...
}

// 단순 변수 뿐만 아니라, 객체, 함수도 가능
export { foo, spam, add, Person };
```



다른 모듈에서 선언해주어야 하는 것

```js
// main.js

// variables 모듈에 선언된 이름을 사용하기 위해 import 
import { foo, spam } from './variables.js';

console.log(foo);
console.log(spam);

```






<br></br>

___

### 선언과 동시에 Export 하기
___


```js
// common.js
export const foo = 'bar';
export const spam = 'eggs';
export function add(x, y) {
  return x + y;
}
export class Person {
  // ...
}
```







<br></br>

___

### Default Export
___



모듈을 대표하는 `하나의 값`을 지정. 1 개의 모듈에는 1개의 `default export` 만 존재


```js
// foo.js
export default 'bar';

// add.js
export default function (x, y) {
  return x + y;
}
```

Import 에서는 중괄호 {} 를 제외하고 호출한다

```js
// main.js
import foo from './foo.js'
import add from './add.js';

console.log(foo); // bar
console.log(add(1, 2)); // 3
```







<br></br>

___

### 원하는 이름으로 대체해서 export, import 하기
___


```js
const foo = 'bar';

// export side
export { foo as FOO }; 

// import side
import { Component as Comp } from 'react'; 
```







<br></br>

___

### 모듈 사용 시 주의할 점
___



1. import 구문과 export 구문은 `모듈 간 의존 관계`를 나타내는 것일 뿐

2. 코드를 `실행`시키라는 `명령이 아니라는 것`

3. 같은 모듈을 여러 다른 모듈에서 불러와도, 모듈 내부의 코드는 `단 한 번만 실행`

4. import 구문과 export 구문은 모듈의 `가장 바깥쪽 스코프에서만 사용`할 수 있음


<br />


위의 주의 사항에 대해서 더 자세한 건 수업시간에 실습을 통해 다루도록....










____


<br></br>
## <strong> 3. Today I found out </strong>

1. `comments`

> @import "comments"

<br>

2. comments comments



<br></br>

___
___